insert into public.cotas (id, nome) values (1, 'L10 Esc Publica, Renda<1.5sm, Raca, Def');
insert into public.cotas (id, nome) values (2, 'L1 Esc Publica, Renda<1.5sm');
insert into public.cotas (id, nome) values (3, 'Ampla Concorrência');
insert into public.cotas (id, nome) values (4, 'L5 Esc Publica, Indep. Renda');
insert into public.cotas (id, nome) values (5, 'Não possui');
insert into public.cotas (id, nome) values (6, 'L6 Esc Publica, Indep. Renda, Raca');
insert into public.cotas (id, nome) values (7, 'L2 Esc Publica, Renda<1.5sm, Raca');
insert into public.cotas (id, nome) values (8, 'L14 Esc Publica, Indep. Renda, Raca, Def');
insert into public.cotas (id, nome) values (9, 'L13 Esc Publica, Indep. Renda, Def');
insert into public.cotas (id, nome) values (10, 'L9 Esc Publica, Renda<1.5sm, Def');
insert into public.cotas (id, nome) values (11, 'Alunos de Escola Pública, sem comprovação renda');
insert into public.cotas (id, nome) values (12, 'Candidato com deficiência');
insert into public.cotas (id, nome) values (13, 'Alunos de Escola Pública, sem comprovação renda, autodeclarado preto, pardo ou indígena');
insert into public.cotas (id, nome) values (14, 'Candidatos Sem comprovação renda, autodeclarado preto, pardo ou indígena');
insert into public.cotas (id, nome) values (15, 'Ampla Concorrência, Candidatos que cursaram todo o Ensino Médio em escolas regulares e presenciais, públicas e privadas dos municípios da UF da Instituição');
insert into public.cotas (id, nome) values (16, 'Servidor da Rede Federal de Educação Profissional, Científica e Tecnológica');

insert into public.cursos(id, nome) values (1, 'Licenciatura em Matemática');
insert into public.cursos(id, nome) values (2, 'Tecnologia em Hotelaria');
insert into public.cursos(id, nome) values (3, 'Técnico em Segurança do Trabalho');
insert into public.cursos(id, nome) values (4, 'Tecnologia em Mecatrônica Industrial');
insert into public.cursos(id, nome) values (5, 'Tecnologia em Estradas');
insert into public.cursos(id, nome) values (6, 'Mestrado em Engenharia de Telecomunicações');
insert into public.cursos(id, nome) values (7, 'Licenciatura em Teatro');
insert into public.cursos(id, nome) values (8, 'Licenciatura em Física');
insert into public.cursos(id, nome) values (9, 'Bacharelado em Engenharia de Mecatrônica');
insert into public.cursos(id, nome) values (10, 'Licenciatura em Matemática');
insert into public.cursos(id, nome) values (11, 'Técnico em Manutenção Automotiva');
insert into public.cursos(id, nome) values (12, 'Integrado em Eletrotécnica');
insert into public.cursos(id, nome) values (13, 'Bacharelado em Engenharia de Computação');
insert into public.cursos(id, nome) values (14, 'Mestrado em Propriedade Intelectual e Transferência de Tecnologia para Inovação');
insert into public.cursos(id, nome) values (15, 'Técnico em Edificações');
insert into public.cursos(id, nome) values (16, 'Técnico em Instrumento Musical');
insert into public.cursos(id, nome) values (17, 'Bacharelado em Engenharia Civil');
insert into public.cursos(id, nome) values (18, 'Tecnologia em Processos Químicos');
insert into public.cursos(id, nome) values (19, 'Bacharelado em Engenharia de Telecomunicações');
insert into public.cursos(id, nome) values (20, 'Tecnologia em Telemática');
insert into public.cursos(id, nome) values (21, 'Integrado em Mecânica Industrial');
insert into public.cursos(id, nome) values (22, 'Tecnologia em Gestão Desportiva e de Lazer');
insert into public.cursos(id, nome) values (23, 'Mestrado em Ensino  de Ciências e Matemática');
insert into public.cursos(id, nome) values (24, 'Integrado em Telecomunicações');
insert into public.cursos(id, nome) values (25, 'Técnico em Mecânica Industrial');
insert into public.cursos(id, nome) values (26, 'Bacharelado em Turismo');
insert into public.cursos(id, nome) values (27, 'Mestrado Profissional em Artes');
insert into public.cursos(id, nome) values (28, 'Integrado em Edificações');
insert into public.cursos(id, nome) values (29, 'Integrado em Informática');
insert into public.cursos(id, nome) values (30, 'Licenciatura em Artes Visuais');
insert into public.cursos(id, nome) values (31, 'Integrado em Química');
insert into public.cursos(id, nome) values (32, 'Tecnologia em Gestão Ambiental');
insert into public.cursos(id, nome) values (33, 'Técnico em Eletrotécnica');
insert into public.cursos(id, nome) values (34, 'Tecnologia em Saneamento Ambiental');
insert into public.cursos(id, nome) values (35, 'Mestrado Acadêmico em Ciência da Computação');
insert into public.cursos(id, nome) values (36, 'Integrado em Mecânica');
insert into public.cursos(id, nome) values (37, 'Bacharelado em Sistemas de Informação');
insert into public.cursos(id, nome) values (38, 'Tecnologia em Construção de Edifícios (produção Civil)');
insert into public.cursos(id, nome) values (39, 'Técnico em Sistemas de Energia Renovável');
insert into public.cursos(id, nome) values (40, 'Bacharelado em Engenharia Ambiental');
insert into public.cursos(id, nome) values (41, 'Tecnologia em Automação Industrial');
insert into public.cursos(id, nome) values (42, 'Licenciatura em Educação Física');
insert into public.cursos(id, nome) values (43, 'Técnico em Geoprocessamento');
insert into public.cursos(id, nome) values (44, 'Integrado em Mecânica Industrial - Proeja');
insert into public.cursos(id, nome) values (45, 'Bacharelado em Ciência da Computação');
insert into public.cursos(id, nome) values (46, 'Técnico em Meio Ambiente');
insert into public.cursos(id, nome) values (47, 'Bacharelado em Engenharia Ambiental e Sanitária');
insert into public.cursos(id, nome) values (48, 'Técnico em Redes de Computadores');
insert into public.cursos(id, nome) values (49, 'Técnico em Automação Industrial');
insert into public.cursos(id, nome) values (50, 'Técnico em Química');
insert into public.cursos(id, nome) values (51, 'Licenciatura em Química');
insert into public.cursos(id, nome) values (52, 'Bacharelado em Engenharia Mecânica');
insert into public.cursos(id, nome) values (53, 'Técnico em Informática');
insert into public.cursos(id, nome) values (54, 'Técnico em Mecânica');
insert into public.cursos(id, nome) values (55, 'Técnico Subsequente em Meio Ambiente');
insert into public.cursos(id, nome) values (56, 'Licenciatura em Geografia');
insert into public.cursos(id, nome) values (57, 'Bacharelado em Engenharia de Produção Civil');
insert into public.cursos(id, nome) values (58, 'Tecnologia em Irrigação e Drenagem');
insert into public.cursos(id, nome) values (59, 'Técnico em Agropecuária');
insert into public.cursos(id, nome) values (60, 'Especialização em Gestão da Qualidade e Segurança dos Alimentos');
insert into public.cursos(id, nome) values (61, 'Técnico em Agroindústria');
insert into public.cursos(id, nome) values (62, 'Técnico em Fruticultura');
insert into public.cursos(id, nome) values (63, 'Tecnologia em Alimentos');
insert into public.cursos(id, nome) values (64, 'Especialização em Gestão Ambiental');
insert into public.cursos(id, nome) values (65, 'Técnico em Panificação');
insert into public.cursos(id, nome) values (66, 'Mestrado Nacional Profissional em Ensino de Física');
insert into public.cursos(id, nome) values (67, 'Técnico em Eletroeletrônica');
insert into public.cursos(id, nome) values (68, 'Bacharelado em Agronomia');
insert into public.cursos(id, nome) values (69, 'Técnico Integrado em Eletrotécnica');
insert into public.cursos(id, nome) values (70, 'Licenciatura em Música');
insert into public.cursos(id, nome) values (71, 'Técnico Integrado em Química');
insert into public.cursos(id, nome) values (72, 'Mestrado em Tecnologia de Alimentos');
insert into public.cursos(id, nome) values (73, 'Integrado em Nutrição e Dietética');
insert into public.cursos(id, nome) values (74, 'Integrado em Agroindústria');
insert into public.cursos(id, nome) values (75, 'Técnico em Nutrição e Dietética');
insert into public.cursos(id, nome) values (76, 'Técnico Integrado em Informática');
insert into public.cursos(id, nome) values (77, 'Integrado em Agropecuária');
insert into public.cursos(id, nome) values (78, 'Bacharelado em Serviço Social');
insert into public.cursos(id, nome) values (79, 'Técnico em Zootecnia');
insert into public.cursos(id, nome) values (80, 'Bacharelado em Engenharia Agrícola');
insert into public.cursos(id, nome) values (81, 'Técnico em Comércio');
insert into public.cursos(id, nome) values (82, 'Bacharelado em Zootecnia');
insert into public.cursos(id, nome) values (83, 'Especialização em Gestão e Manejo de Recursos Ambientais');
insert into public.cursos(id, nome) values (84, 'Especialização em Produção Animal no Semiárido');
insert into public.cursos(id, nome) values (85, 'Especialização em Manejo Sustentável da Irrigação para o Desenvolvimento dos Sistemas Agrícolas');
insert into public.cursos(id, nome) values (86, 'Tecnologia em Redes de Computadores');
insert into public.cursos(id, nome) values (87, 'Técnico Subsequente em Informática');
insert into public.cursos(id, nome) values (88, 'Tecnologia em Gestão de Turismo');
insert into public.cursos(id, nome) values (89, 'Integrado em Eventos');
insert into public.cursos(id, nome) values (90, 'Licenciatura em Pedagogia');
insert into public.cursos(id, nome) values (91, 'Técnico Integrado em Eletrônica');
insert into public.cursos(id, nome) values (92, 'Técnico em Restaurante e Bar');
insert into public.cursos(id, nome) values (93, 'Técnico em Aquicultura');
insert into public.cursos(id, nome) values (94, 'Técnico em Eventos');
insert into public.cursos(id, nome) values (95, 'Licenciatura em Ciências Biológicas');
insert into public.cursos(id, nome) values (96, 'Técnico em Construção Naval');
insert into public.cursos(id, nome) values (97, 'Licenciatura em Letras - Português e Inglês');
insert into public.cursos(id, nome) values (98, 'Técnico em Alimentos - Vespertino');
insert into public.cursos(id, nome) values (99, 'Técnico em Agricultura');
insert into public.cursos(id, nome) values (100, 'Licenciatura em Letras - Português Inglês');
insert into public.cursos(id, nome) values (101, 'Técnico em Guia de Turismo');
insert into public.cursos(id, nome) values (102, 'Bacharelado em Engenharia de Aquicultura');
insert into public.cursos(id, nome) values (103, 'Técnico em Petroquímica');
insert into public.cursos(id, nome) values (104, 'Técnico em Administração');
insert into public.cursos(id, nome) values (105, 'Tecnologia em Gastronomia');
insert into public.cursos(id, nome) values (106, 'Técnico Integrado em Comércio');
insert into public.cursos(id, nome) values (107, 'Técnico em Eletromecânica');
insert into public.cursos(id, nome) values (108, 'Técnico Integrado em Informática para Internet');
insert into public.cursos(id, nome) values (109, 'Técnico Integrado em Automação Industrial');
insert into public.cursos(id, nome) values (110, 'Técnico Subsequente em Soldagem');
insert into public.cursos(id, nome) values (111, 'Técnico Subsequente em Administração');
insert into public.cursos(id, nome) values (112, 'Curso Técnico Integrado em Petróleo e Gás');
insert into public.cursos(id, nome) values (113, 'Curso Técnico Integrado em Manutenção Automotiva');
insert into public.cursos(id, nome) values (114, 'Licenciatura  em  Letras Português/inglês e Suas Respectivas Literaturas');
insert into public.cursos(id, nome) values (115, 'Licenciatura Plena em Química');
insert into public.cursos(id, nome) values (116, 'Tecnologia em Agroindustria');
insert into public.cursos(id, nome) values (117, 'Técnico em Alimentos');
insert into public.cursos(id, nome) values (118, 'Técnico em Logística');
insert into public.cursos(id, nome) values (119, 'Curso Técnico Integrado em Eletroeletrônica');
insert into public.cursos(id, nome) values (120, 'Curso Técnico Integrado em Metalurgia');
insert into public.cursos(id, nome) values (121, 'Curso Técnico Integrado em Química');
insert into public.cursos(id, nome) values (122, 'Técnico em Manutenção e Suporte em Informática');
insert into public.cursos(id, nome) values (123, 'Técnico em Hospedagem');
insert into public.cursos(id, nome) values (124, 'Técnico em Computação Gráfica');
insert into public.cursos(id, nome) values (125, 'Técnico Subsequente em Edificações');
insert into public.cursos(id, nome) values (126, 'Técnico Subsequente em Mecânica');
insert into public.cursos(id, nome) values (127, 'Técnico Subsequente em Agropecuária');
insert into public.cursos(id, nome) values (128, 'Técnico Integrado em Redes de Computadores');
insert into public.cursos(id, nome) values (129, 'Mestrado em Tecnologia e Gestão Ambiental');
insert into public.cursos(id, nome) values (130, 'Mestrado em Energias Renováveis');
insert into public.cursos(id, nome) values (131, 'Bacharelado em Engenharia de Controle e Automação');
insert into public.cursos(id, nome) values (132, 'Técnico Subsequente em Química');
insert into public.cursos(id, nome) values (133, 'Tecnologia em Análise e Desenvolvimento de Sistemas');
insert into public.cursos(id, nome) values (134, 'Especialização  em Meio Ambiente e Desenvolvimento Regional');
insert into public.cursos(id, nome) values (135, 'Técnico em Pesca');
insert into public.cursos(id, nome) values (136, 'Licenciatura em Letras');
insert into public.cursos(id, nome) values (137, 'Mestrado Profissional em Ensino e Formação Docente');
insert into public.cursos(id, nome) values (138, 'Mestrado em Educação Profissional e Tecnológica');
insert into public.cursos(id, nome) values (139, 'Licenciatura em Matemática Uab');
insert into public.cursos(id, nome) values (140, 'Bacharelado em Nutrição');
insert into public.cursos(id, nome) values (141, 'Especialização em Gestão de Micro, Pequenas e Médias Empresas');
insert into public.cursos(id, nome) values (142, 'Especialização em Desenvolvimento Sustentável');
insert into public.cursos(id, nome) values (143, 'Técnico Integrado em Aquicultura');
insert into public.cursos(id, nome) values (144, 'Técnico em Edificações - Subsequente');
insert into public.cursos(id, nome) values (145, 'Especialização em Teoria, Metodologia e Práticas de Ensino');
insert into public.cursos(id, nome) values (146, 'Técnico Integrado em Eletromecânica');

insert into public.situacoes_periodo(id, nome)  values (1, 'Falecido');
insert into public.situacoes_periodo(id, nome)  values (2, 'Pediu Vínculo Institucional');
insert into public.situacoes_periodo(id, nome)  values (3, 'Fechado c/ Pendência');
insert into public.situacoes_periodo(id, nome)  values (4, 'Aprovado Parcialmente');
insert into public.situacoes_periodo(id, nome)  values (5, 'Reprovado');
insert into public.situacoes_periodo(id, nome)  values (6, 'Em Aberto');
insert into public.situacoes_periodo(id, nome)  values (7, 'Pediu Transf. Externa');
insert into public.situacoes_periodo(id, nome)  values (8, 'Abandonou');
insert into public.situacoes_periodo(id, nome)  values (9, 'Aprov. c/Dependência');
insert into public.situacoes_periodo(id, nome)  values (10, 'Rep. Falta');
insert into public.situacoes_periodo(id, nome)  values (11, 'Transferido Interno');
insert into public.situacoes_periodo(id, nome)  values (12, 'Aprovado');
insert into public.situacoes_periodo(id, nome)  values (13, 'Trancou');
insert into public.situacoes_periodo(id, nome)  values (14, 'Cancelou Compulsório');
insert into public.situacoes_periodo(id, nome)  values (15, 'Matriculado');
insert into public.situacoes_periodo(id, nome)  values (16, 'Cancelou');


insert into public.situacoes_matricula(id, nome)  values (1,'Vínculo Institucional');
insert into public.situacoes_matricula(id, nome)  values (2,'Concludente');
insert into public.situacoes_matricula(id, nome)  values (3,'Concluído');
insert into public.situacoes_matricula(id, nome)  values (4,'Falecido');
insert into public.situacoes_matricula(id, nome)  values (5,'Transferido Externo');
insert into public.situacoes_matricula(id, nome)  values (6,'Abandono');
insert into public.situacoes_matricula(id, nome)  values (7,'Transferido Interno');
insert into public.situacoes_matricula(id, nome)  values (8,'Trancado');
insert into public.situacoes_matricula(id, nome)  values (9,'Cancelado Compulsoriamente');
insert into public.situacoes_matricula(id, nome)  values (10,'Matriculado');
insert into public.situacoes_matricula(id, nome)  values (11,'Cancelado Voluntariamente');