INSERT INTO public.cotas (id, nome) VALUES (1, 'L10 Esc Publica, Renda<1.5sm, Raca, Def');
INSERT INTO public.cotas (id, nome) VALUES (2, 'L1 Esc Publica, Renda<1.5sm');
INSERT INTO public.cotas (id, nome) VALUES (3, 'Ampla Concorrência');
INSERT INTO public.cotas (id, nome) VALUES (4, 'L5 Esc Publica, Indep. Renda');
INSERT INTO public.cotas (id, nome) VALUES (5, 'Não possui');
INSERT INTO public.cotas (id, nome) VALUES (6, 'L6 Esc Publica, Indep. Renda, Raca');
INSERT INTO public.cotas (id, nome) VALUES (7, 'L2 Esc Publica, Renda<1.5sm, Raca');
INSERT INTO public.cotas (id, nome) VALUES (8, 'L14 Esc Publica, Indep. Renda, Raca, Def');
INSERT INTO public.cotas (id, nome) VALUES (9, 'L13 Esc Publica, Indep. Renda, Def');
INSERT INTO public.cotas (id, nome) VALUES (10, 'L9 Esc Publica, Renda<1.5sm, Def');
INSERT INTO public.cotas (id, nome) VALUES (11, 'Alunos de Escola Pública, sem comprovação renda');
INSERT INTO public.cotas (id, nome) VALUES (12, 'Candidato com deficiência');
INSERT INTO public.cotas (id, nome) VALUES (13, 'Alunos de Escola Pública, sem comprovação renda, autodeclarado preto, pardo ou indígena');
INSERT INTO public.cotas (id, nome) VALUES (14, 'Candidatos Sem comprovação renda, autodeclarado preto, pardo ou indígena');
INSERT INTO public.cotas (id, nome) VALUES (15, 'Ampla Concorrência, Candidatos que cursaram todo o Ensino Médio em escolas regulares e presenciais, públicas e privadas dos municípios da UF da Instituição');
INSERT INTO public.cotas (id, nome) VALUES (16, 'Servidor da Rede Federal de Educação Profissional, Científica e Tecnológica');

INSERT INTO public.campus (id, nome, slug, lat, lng) VALUES (1, 'Fortaleza', 'CAMPUS_FORTALEZA', -3.744168, -38.536017);
INSERT INTO public.campus (id, nome, slug, lat, lng) VALUES (2, 'Acaraú', 'CAMPUS_ACARAÚ', -2.888987, -40.113683);
INSERT INTO public.campus (id, nome, slug, lat, lng) VALUES (3, 'Acopiara', 'CAMPUS_ACOPIARA', -6.066097, -39.474898);
INSERT INTO public.campus (id, nome, slug, lat, lng) VALUES (4, 'Aracati', 'CAMPUS_ARACATI', -4.567205, -37.791689);
INSERT INTO public.campus (id, nome, slug, lat, lng) VALUES (5, 'Baturité', 'CAMPUS_BATURITÉ', -4.343535, -38.864409);
INSERT INTO public.campus (id, nome, slug, lat, lng) VALUES (6, 'Boa Viagem', 'CAMPUS_BOA_VIAGEM', -5.083728, -39.707292);
INSERT INTO public.campus (id, nome, slug, lat, lng) VALUES (7, 'Camocim', 'CAMPUS_CAMOCIM', -2.898475, -40.860536);
INSERT INTO public.campus (id, nome, slug, lat, lng) VALUES (8, 'Canindé', 'CAMPUS_CANINDÉ', -4.390520, -39.313088);
INSERT INTO public.campus (id, nome, slug, lat, lng) VALUES (9, 'Caucaia', 'CAMPUS_CAUCAIA', -3.731103, -38.672042);
INSERT INTO public.campus (id, nome, slug, lat, lng) VALUES (10, 'Cedro', 'CAMPUS_CEDRO', -6.600770, -39.055429);
INSERT INTO public.campus (id, nome, slug, lat, lng) VALUES (11, 'Crateús', 'CAMPUS_CRATEÚS', -5.172457, -40.657807);
INSERT INTO public.campus (id, nome, slug, lat, lng) VALUES (12, 'Crato', 'CAMPUS_CRATO', -7.206260, -39.448441);
INSERT INTO public.campus (id, nome, slug, lat, lng) VALUES (13, 'Guaramiranga', 'CAMPUS_GUARAMIRANGA', -4.266252, -38.931733);
INSERT INTO public.campus (id, nome, slug, lat, lng) VALUES (14, 'Horizonte', 'CAMPUS_HORIZONTE', -4.114094, -38.481143);
INSERT INTO public.campus (id, nome, slug, lat, lng) VALUES (15, 'Iguatu', 'CAMPUS_IGUATU', -6.352885, -39.305311);
INSERT INTO public.campus (id, nome, slug, lat, lng) VALUES (16, 'Itapipoca', 'CAMPUS_ITAPIPOCA', -3.489359, -39.569694);
INSERT INTO public.campus (id, nome, slug, lat, lng) VALUES (17, 'Jaguaribe', 'CAMPUS_JAGUARIBE', -5.879567, -38.609862);
INSERT INTO public.campus (id, nome, slug, lat, lng) VALUES (18, 'Jaguaruana', 'CAMPUS_JAGUARUANA', -4.838393, -37.785118);
INSERT INTO public.campus (id, nome, slug, lat, lng) VALUES (19, 'Juazeiro do Norte', 'CAMPUS_JUAZEIRO_DO_NORTE', -7.244480, -39.306325);
INSERT INTO public.campus (id, nome, slug, lat, lng) VALUES (20, 'Limoeiro do Norte', 'CAMPUS_LIMOEIRO_DO_NORTE', -5.145887, -38.093767);
INSERT INTO public.campus (id, nome, slug, lat, lng) VALUES (21, 'Maracanaú', 'CAMPUS_MARACANAÚ', -3.872191, -38.611336);
INSERT INTO public.campus (id, nome, slug, lat, lng) VALUES (22, 'Maranguape', 'CAMPUS_MARANGUAPE', -3.917105, -38.684209);
INSERT INTO public.campus (id, nome, slug, lat, lng) VALUES (23, 'Morada Nova', 'CAMPUS_MORADA_NOVA', -5.091549, -38.364843);
INSERT INTO public.campus (id, nome, slug, lat, lng) VALUES (24, 'Paracuru', 'CAMPUS_PARACURU', -3.444986, -39.041361);
INSERT INTO public.campus (id, nome, slug, lat, lng) VALUES (25, 'Pecém', 'CAMPUS_PECÉM', -3.654260, -38.857476);
INSERT INTO public.campus (id, nome, slug, lat, lng) VALUES (26, 'Quixadá', 'CAMPUS_QUIXADÁ', -4.978481, -39.057757);
INSERT INTO public.campus (id, nome, slug, lat, lng) VALUES (27, 'Sobral', 'CAMPUS_SOBRAL', -3.683167, -40.341537);
INSERT INTO public.campus (id, nome, slug, lat, lng) VALUES (28, 'Tabuleiro do Norte', 'CAMPUS_TABULEIRO_DO_NORTE', -5.236826, -38.145111);
INSERT INTO public.campus (id, nome, slug, lat, lng) VALUES (29, 'Tauá', 'CAMPUS_TAUÁ', -6.002172, -40.300255);
INSERT INTO public.campus (id, nome, slug, lat, lng) VALUES (30, 'Tianguá', 'CAMPUS_TIANGUÁ', -3.733322, -41.012236);
INSERT INTO public.campus (id, nome, slug, lat, lng) VALUES (31, 'Ubajara', 'CAMPUS_UBAJARA', -3.844784, -40.917503);
INSERT INTO public.campus (id, nome, slug, lat, lng) VALUES (32, 'Umirim', 'CAMPUS_UMIRIM', -3.687309, -39.344834);

INSERT INTO public.cursos(id, nome) VALUES (1, 'Licenciatura em Matemática');
INSERT INTO public.cursos(id, nome) VALUES (2, 'Tecnologia em Hotelaria');
INSERT INTO public.cursos(id, nome) VALUES (3, 'Técnico em Segurança do Trabalho');
INSERT INTO public.cursos(id, nome) VALUES (4, 'Tecnologia em Mecatrônica Industrial');
INSERT INTO public.cursos(id, nome) VALUES (5, 'Tecnologia em Estradas');
INSERT INTO public.cursos(id, nome) VALUES (6, 'Mestrado em Engenharia de Telecomunicações');
INSERT INTO public.cursos(id, nome) VALUES (7, 'Licenciatura em Teatro');
INSERT INTO public.cursos(id, nome) VALUES (8, 'Licenciatura em Física');
INSERT INTO public.cursos(id, nome) VALUES (9, 'Bacharelado em Engenharia de Mecatrônica');
INSERT INTO public.cursos(id, nome) VALUES (10, 'Licenciatura em Matemática');
INSERT INTO public.cursos(id, nome) VALUES (11, 'Técnico em Manutenção Automotiva');
INSERT INTO public.cursos(id, nome) VALUES (12, 'Integrado em Eletrotécnica');
INSERT INTO public.cursos(id, nome) VALUES (13, 'Bacharelado em Engenharia de Computação');
INSERT INTO public.cursos(id, nome) VALUES (14, 'Mestrado em Propriedade Intelectual e Transferência de Tecnologia para Inovação');
INSERT INTO public.cursos(id, nome) VALUES (15, 'Técnico em Edificações');
INSERT INTO public.cursos(id, nome) VALUES (16, 'Técnico em Instrumento Musical');
INSERT INTO public.cursos(id, nome) VALUES (17, 'Bacharelado em Engenharia Civil');
INSERT INTO public.cursos(id, nome) VALUES (18, 'Tecnologia em Processos Químicos');
INSERT INTO public.cursos(id, nome) VALUES (19, 'Bacharelado em Engenharia de Telecomunicações');
INSERT INTO public.cursos(id, nome) VALUES (20, 'Tecnologia em Telemática');
INSERT INTO public.cursos(id, nome) VALUES (21, 'Integrado em Mecânica Industrial');
INSERT INTO public.cursos(id, nome) VALUES (22, 'Tecnologia em Gestão Desportiva e de Lazer');
INSERT INTO public.cursos(id, nome) VALUES (23, 'Mestrado em Ensino  de Ciências e Matemática');
INSERT INTO public.cursos(id, nome) VALUES (24, 'Integrado em Telecomunicações');
INSERT INTO public.cursos(id, nome) VALUES (25, 'Técnico em Mecânica Industrial');
INSERT INTO public.cursos(id, nome) VALUES (26, 'Bacharelado em Turismo');
INSERT INTO public.cursos(id, nome) VALUES (27, 'Mestrado Profissional em Artes');
INSERT INTO public.cursos(id, nome) VALUES (28, 'Integrado em Edificações');
INSERT INTO public.cursos(id, nome) VALUES (29, 'Integrado em Informática');
INSERT INTO public.cursos(id, nome) VALUES (30, 'Licenciatura em Artes Visuais');
INSERT INTO public.cursos(id, nome) VALUES (31, 'Integrado em Química');
INSERT INTO public.cursos(id, nome) VALUES (32, 'Tecnologia em Gestão Ambiental');
INSERT INTO public.cursos(id, nome) VALUES (33, 'Técnico em Eletrotécnica');
INSERT INTO public.cursos(id, nome) VALUES (34, 'Tecnologia em Saneamento Ambiental');
INSERT INTO public.cursos(id, nome) VALUES (35, 'Mestrado Acadêmico em Ciência da Computação');
INSERT INTO public.cursos(id, nome) VALUES (36, 'Integrado em Mecânica');
INSERT INTO public.cursos(id, nome) VALUES (37, 'Bacharelado em Sistemas de Informação');
INSERT INTO public.cursos(id, nome) VALUES (38, 'Tecnologia em Construção de Edifícios (produção Civil)');
INSERT INTO public.cursos(id, nome) VALUES (39, 'Técnico em Sistemas de Energia Renovável');
INSERT INTO public.cursos(id, nome) VALUES (40, 'Bacharelado em Engenharia Ambiental');
INSERT INTO public.cursos(id, nome) VALUES (41, 'Tecnologia em Automação Industrial');
INSERT INTO public.cursos(id, nome) VALUES (42, 'Licenciatura em Educação Física');
INSERT INTO public.cursos(id, nome) VALUES (43, 'Técnico em Geoprocessamento');
INSERT INTO public.cursos(id, nome) VALUES (44, 'Integrado em Mecânica Industrial - Proeja');
INSERT INTO public.cursos(id, nome) VALUES (45, 'Bacharelado em Ciência da Computação');
INSERT INTO public.cursos(id, nome) VALUES (46, 'Técnico em Meio Ambiente');
INSERT INTO public.cursos(id, nome) VALUES (47, 'Bacharelado em Engenharia Ambiental e Sanitária');
INSERT INTO public.cursos(id, nome) VALUES (48, 'Técnico em Redes de Computadores');
INSERT INTO public.cursos(id, nome) VALUES (49, 'Técnico em Automação Industrial');
INSERT INTO public.cursos(id, nome) VALUES (50, 'Técnico em Química');
INSERT INTO public.cursos(id, nome) VALUES (51, 'Licenciatura em Química');
INSERT INTO public.cursos(id, nome) VALUES (52, 'Bacharelado em Engenharia Mecânica');
INSERT INTO public.cursos(id, nome) VALUES (53, 'Técnico em Informática');
INSERT INTO public.cursos(id, nome) VALUES (54, 'Técnico em Mecânica');
INSERT INTO public.cursos(id, nome) VALUES (55, 'Técnico Subsequente em Meio Ambiente');
INSERT INTO public.cursos(id, nome) VALUES (56, 'Licenciatura em Geografia');
INSERT INTO public.cursos(id, nome) VALUES (57, 'Bacharelado em Engenharia de Produção Civil');
INSERT INTO public.cursos(id, nome) VALUES (58, 'Tecnologia em Irrigação e Drenagem');
INSERT INTO public.cursos(id, nome) VALUES (59, 'Técnico em Agropecuária');
INSERT INTO public.cursos(id, nome) VALUES (60, 'Especialização em Gestão da Qualidade e Segurança dos Alimentos');
INSERT INTO public.cursos(id, nome) VALUES (61, 'Técnico em Agroindústria');
INSERT INTO public.cursos(id, nome) VALUES (62, 'Técnico em Fruticultura');
INSERT INTO public.cursos(id, nome) VALUES (63, 'Tecnologia em Alimentos');
INSERT INTO public.cursos(id, nome) VALUES (64, 'Especialização em Gestão Ambiental');
INSERT INTO public.cursos(id, nome) VALUES (65, 'Técnico em Panificação');
INSERT INTO public.cursos(id, nome) VALUES (66, 'Mestrado Nacional Profissional em Ensino de Física');
INSERT INTO public.cursos(id, nome) VALUES (67, 'Técnico em Eletroeletrônica');
INSERT INTO public.cursos(id, nome) VALUES (68, 'Bacharelado em Agronomia');
INSERT INTO public.cursos(id, nome) VALUES (69, 'Técnico Integrado em Eletrotécnica');
INSERT INTO public.cursos(id, nome) VALUES (70, 'Licenciatura em Música');
INSERT INTO public.cursos(id, nome) VALUES (71, 'Técnico Integrado em Química');
INSERT INTO public.cursos(id, nome) VALUES (72, 'Mestrado em Tecnologia de Alimentos');
INSERT INTO public.cursos(id, nome) VALUES (73, 'Integrado em Nutrição e Dietética');
INSERT INTO public.cursos(id, nome) VALUES (74, 'Integrado em Agroindústria');
INSERT INTO public.cursos(id, nome) VALUES (75, 'Técnico em Nutrição e Dietética');
INSERT INTO public.cursos(id, nome) VALUES (76, 'Técnico Integrado em Informática');
INSERT INTO public.cursos(id, nome) VALUES (77, 'Integrado em Agropecuária');
INSERT INTO public.cursos(id, nome) VALUES (78, 'Bacharelado em Serviço Social');
INSERT INTO public.cursos(id, nome) VALUES (79, 'Técnico em Zootecnia');
INSERT INTO public.cursos(id, nome) VALUES (80, 'Bacharelado em Engenharia Agrícola');
INSERT INTO public.cursos(id, nome) VALUES (81, 'Técnico em Comércio');
INSERT INTO public.cursos(id, nome) VALUES (82, 'Bacharelado em Zootecnia');
INSERT INTO public.cursos(id, nome) VALUES (83, 'Especialização em Gestão e Manejo de Recursos Ambientais');
INSERT INTO public.cursos(id, nome) VALUES (84, 'Especialização em Produção Animal no Semiárido');
INSERT INTO public.cursos(id, nome) VALUES (85, 'Especialização em Manejo Sustentável da Irrigação para o Desenvolvimento dos Sistemas Agrícolas');
INSERT INTO public.cursos(id, nome) VALUES (86, 'Tecnologia em Redes de Computadores');
INSERT INTO public.cursos(id, nome) VALUES (87, 'Técnico Subsequente em Informática');
INSERT INTO public.cursos(id, nome) VALUES (88, 'Tecnologia em Gestão de Turismo');
INSERT INTO public.cursos(id, nome) VALUES (89, 'Integrado em Eventos');
INSERT INTO public.cursos(id, nome) VALUES (90, 'Licenciatura em Pedagogia');
INSERT INTO public.cursos(id, nome) VALUES (91, 'Técnico Integrado em Eletrônica');
INSERT INTO public.cursos(id, nome) VALUES (92, 'Técnico em Restaurante e Bar');
INSERT INTO public.cursos(id, nome) VALUES (93, 'Técnico em Aquicultura');
INSERT INTO public.cursos(id, nome) VALUES (94, 'Técnico em Eventos');
INSERT INTO public.cursos(id, nome) VALUES (95, 'Licenciatura em Ciências Biológicas');
INSERT INTO public.cursos(id, nome) VALUES (96, 'Técnico em Construção Naval');
INSERT INTO public.cursos(id, nome) VALUES (97, 'Licenciatura em Letras - Português e Inglês');
INSERT INTO public.cursos(id, nome) VALUES (98, 'Técnico em Alimentos - Vespertino');
INSERT INTO public.cursos(id, nome) VALUES (99, 'Técnico em Agricultura');
INSERT INTO public.cursos(id, nome) VALUES (100, 'Licenciatura em Letras - Português Inglês');
INSERT INTO public.cursos(id, nome) VALUES (101, 'Técnico em Guia de Turismo');
INSERT INTO public.cursos(id, nome) VALUES (102, 'Bacharelado em Engenharia de Aquicultura');
INSERT INTO public.cursos(id, nome) VALUES (103, 'Técnico em Petroquímica');
INSERT INTO public.cursos(id, nome) VALUES (104, 'Técnico em Administração');
INSERT INTO public.cursos(id, nome) VALUES (105, 'Tecnologia em Gastronomia');
INSERT INTO public.cursos(id, nome) VALUES (106, 'Técnico Integrado em Comércio');
INSERT INTO public.cursos(id, nome) VALUES (107, 'Técnico em Eletromecânica');
INSERT INTO public.cursos(id, nome) VALUES (108, 'Técnico Integrado em Informática para Internet');
INSERT INTO public.cursos(id, nome) VALUES (109, 'Técnico Integrado em Automação Industrial');
INSERT INTO public.cursos(id, nome) VALUES (110, 'Técnico Subsequente em Soldagem');
INSERT INTO public.cursos(id, nome) VALUES (111, 'Técnico Subsequente em Administração');
INSERT INTO public.cursos(id, nome) VALUES (112, 'Curso Técnico Integrado em Petróleo e Gás');
INSERT INTO public.cursos(id, nome) VALUES (113, 'Curso Técnico Integrado em Manutenção Automotiva');
INSERT INTO public.cursos(id, nome) VALUES (114, 'Licenciatura  em  Letras Português/inglês e Suas Respectivas Literaturas');
INSERT INTO public.cursos(id, nome) VALUES (115, 'Licenciatura Plena em Química');
INSERT INTO public.cursos(id, nome) VALUES (116, 'Tecnologia em Agroindustria');
INSERT INTO public.cursos(id, nome) VALUES (117, 'Técnico em Alimentos');
INSERT INTO public.cursos(id, nome) VALUES (118, 'Técnico em Logística');
INSERT INTO public.cursos(id, nome) VALUES (119, 'Curso Técnico Integrado em Eletroeletrônica');
INSERT INTO public.cursos(id, nome) VALUES (120, 'Curso Técnico Integrado em Metalurgia');
INSERT INTO public.cursos(id, nome) VALUES (121, 'Curso Técnico Integrado em Química');
INSERT INTO public.cursos(id, nome) VALUES (122, 'Técnico em Manutenção e Suporte em Informática');
INSERT INTO public.cursos(id, nome) VALUES (123, 'Técnico em Hospedagem');
INSERT INTO public.cursos(id, nome) VALUES (124, 'Técnico em Computação Gráfica');
INSERT INTO public.cursos(id, nome) VALUES (125, 'Técnico Subsequente em Edificações');
INSERT INTO public.cursos(id, nome) VALUES (126, 'Técnico Subsequente em Mecânica');
INSERT INTO public.cursos(id, nome) VALUES (127, 'Técnico Subsequente em Agropecuária');
INSERT INTO public.cursos(id, nome) VALUES (128, 'Técnico Integrado em Redes de Computadores');
INSERT INTO public.cursos(id, nome) VALUES (129, 'Mestrado em Tecnologia e Gestão Ambiental');
INSERT INTO public.cursos(id, nome) VALUES (130, 'Mestrado em Energias Renováveis');
INSERT INTO public.cursos(id, nome) VALUES (131, 'Bacharelado em Engenharia de Controle e Automação');
INSERT INTO public.cursos(id, nome) VALUES (132, 'Técnico Subsequente em Química');
INSERT INTO public.cursos(id, nome) VALUES (133, 'Tecnologia em Análise e Desenvolvimento de Sistemas');
INSERT INTO public.cursos(id, nome) VALUES (134, 'Especialização  em Meio Ambiente e Desenvolvimento Regional');
INSERT INTO public.cursos(id, nome) VALUES (135, 'Técnico em Pesca');
INSERT INTO public.cursos(id, nome) VALUES (136, 'Licenciatura em Letras');
INSERT INTO public.cursos(id, nome) VALUES (137, 'Mestrado Profissional em Ensino e Formação Docente');
INSERT INTO public.cursos(id, nome) VALUES (138, 'Mestrado em Educação Profissional e Tecnológica');
INSERT INTO public.cursos(id, nome) VALUES (139, 'Licenciatura em Matemática Uab');
INSERT INTO public.cursos(id, nome) VALUES (140, 'Bacharelado em Nutrição');
INSERT INTO public.cursos(id, nome) VALUES (141, 'Especialização em Gestão de Micro, Pequenas e Médias Empresas');
INSERT INTO public.cursos(id, nome) VALUES (142, 'Especialização em Desenvolvimento Sustentável');
INSERT INTO public.cursos(id, nome) VALUES (143, 'Técnico Integrado em Aquicultura');
INSERT INTO public.cursos(id, nome) VALUES (144, 'Técnico em Edificações - Subsequente');
INSERT INTO public.cursos(id, nome) VALUES (145, 'Especialização em Teoria, Metodologia e Práticas de Ensino');
INSERT INTO public.cursos(id, nome) VALUES (146, 'Técnico Integrado em Eletromecânica');

INSERT INTO public.situacoes_periodo(id, nome)  VALUES (1, 'Falecido');
INSERT INTO public.situacoes_periodo(id, nome)  VALUES (2, 'Pediu Vínculo Institucional');
INSERT INTO public.situacoes_periodo(id, nome)  VALUES (3, 'Fechado c/ Pendência');
INSERT INTO public.situacoes_periodo(id, nome)  VALUES (4, 'Aprovado Parcialmente');
INSERT INTO public.situacoes_periodo(id, nome)  VALUES (5, 'Reprovado');
INSERT INTO public.situacoes_periodo(id, nome)  VALUES (6, 'Em Aberto');
INSERT INTO public.situacoes_periodo(id, nome)  VALUES (7, 'Pediu Transf. Externa');
INSERT INTO public.situacoes_periodo(id, nome)  VALUES (8, 'Abandonou');
INSERT INTO public.situacoes_periodo(id, nome)  VALUES (9, 'Aprov. c/Dependência');
INSERT INTO public.situacoes_periodo(id, nome)  VALUES (10, 'Rep. Falta');
INSERT INTO public.situacoes_periodo(id, nome)  VALUES (11, 'Transferido Interno');
INSERT INTO public.situacoes_periodo(id, nome)  VALUES (12, 'Aprovado');
INSERT INTO public.situacoes_periodo(id, nome)  VALUES (13, 'Trancou');
INSERT INTO public.situacoes_periodo(id, nome)  VALUES (14, 'Cancelou Compulsório');
INSERT INTO public.situacoes_periodo(id, nome)  VALUES (15, 'Matriculado');
INSERT INTO public.situacoes_periodo(id, nome)  VALUES (16, 'Cancelou');

INSERT INTO public.situacoes_matricula(id, nome)  VALUES (1,'Vínculo Institucional');
INSERT INTO public.situacoes_matricula(id, nome)  VALUES (2,'Concludente');
INSERT INTO public.situacoes_matricula(id, nome)  VALUES (3,'Concluído');
INSERT INTO public.situacoes_matricula(id, nome)  VALUES (4,'Falecido');
INSERT INTO public.situacoes_matricula(id, nome)  VALUES (5,'Transferido Externo');
INSERT INTO public.situacoes_matricula(id, nome)  VALUES (6,'Abandono');
INSERT INTO public.situacoes_matricula(id, nome)  VALUES (7,'Transferido Interno');
INSERT INTO public.situacoes_matricula(id, nome)  VALUES (8,'Trancado');
INSERT INTO public.situacoes_matricula(id, nome)  VALUES (9,'Cancelado Compulsoriamente');
INSERT INTO public.situacoes_matricula(id, nome)  VALUES (10,'Matriculado');
INSERT INTO public.situacoes_matricula(id, nome)  VALUES (11,'Cancelado Voluntariamente');